<div id="welcome">
    <h2><?php print $this->translate(sprintf("Welcome to the Daily Logs application!")); ?></h2>
    <h3><?php print $this->translate('This is the daily logs main page'); ?></h3>
    <div id="more-information">
        <p>
            <?php print $this->translate('Helpful Links:'); ?>
            <ul>
                <li><a href="<?php print $this->url(array(), 'log-add'); ?>"
                title="<?php print $this->translate('add a new log'); ?>"><?php print $this->translate('Add Logs'); ?></a></li>
                <li><a href="<?php print $this->url(array(), 'logs'); ?>"
                title="<?php print $this->translate('view my logs'); ?>"><?php print $this->translate('My Logs'); ?></a></li>
            </ul>
        </p>
    </div>
</div>