<h2><?php print $this->translate('User Logs'); ?></h2>
<?php if (!empty($this->messages)): ?>
    <?php foreach($this->messages as $message): ?>
        <?php print $message; ?>
    <?php endforeach; ?>
<?php endif; ?>
User <?php print $this->userList($this->usersList, $this->selectedUser); ?>
<table width="100%" summary="Daily logs for <?php print ucwords($this->authUser->firstname . ' ' . $this->authUser->lastname); ?>">
    <thead>
        <tr align="left">
            <th><?php print $this->translate('Log Date'); ?></th>
            <th><?php print $this->translate('Username'); ?></th>
            <th><?php print $this->translate('Body'); ?></th>
            <td>&nbsp;</td>
        </tr>
    </thead>
    <tfoot>
        <tr align="left">
            <th colspan="3"><?php print count($this->logs) . $this->translate(' records'); ?></th>
        </tr>
    </tfoot>
    <tbody>
    <?php if (count($this->paginator) > 0): ?>
        <?php echo $this->partialLoop('index/partials/logs/user-record.phtml', $this->paginator); ?>
    <?php endif; ?>
    </tbody>
</table>
<?php echo $this->paginator; ?>