<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' | ');
print $this->doctype('HTML5'); //HTML5 doctype is backwards compatible and therefore safe to use.
?>
<html lang="en-GB">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <link rel="icon" href="/icon.ico" type="image/x-icon" />
        <?php print $this->headMeta(); ?>
        <?php print $this->headTitle(); ?>
        <!-- /#Meta -->

        <!-- /css -->
        <?php
            print $this->headLink()
                       ->prependStylesheet('/css/main.css')
                       ->prependStylesheet('/css/jquery-ui.css');
        ?>
        <!-- /#css -->
        <?php print $this->jQuery(); ?>
        <?php
            if ( $this->ckeditor ) {
                echo $this->headScript()->appendFile('/js/ckeditor/ckeditor.js');
            }
        ?>
    </head>
    <body>
        <div id="wrapper">
            <?php print $this->partial('common/header.phtml'); ?>
            <div id="content">
                <?php print $this->partial('common/navigation.phtml'); ?>
                <div id="body">
                    <?php print $this->layout()->content; ?>
                </div>
            </div>
        </div>
        <!-- /#wrapper -->
        <?php print $this->partial('common/footer.phtml'); ?>
    </body>
</html>