<?php print $this->doctype(); ?>
<html lang="en-GB">
    <head>
        <!-- /meta -->
        <?php print $this->headMeta(); ?>
        <!-- /#meta -->
        <?php print $this->headTitle(); ?>
        <!-- /css -->

        <?php
            print $this->headLink()
                       ->prependStylesheet('/css/main.css')
                       ->prependStylesheet('/css/jquery-ui.css');
        ?>
        <!-- /#css -->
        <?php print $this->jQuery(); ?>
        <?php
            if ($this->ckeditor) {
                print $this->headScript()
                           ->appendFile('/js/ckeditor/ckeditor.js');
            }
        ?>
        <?php
            print $this->headScript()
                    ->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js');
        ?>
    </head>
    <body class="<?php echo $this->placeholder('bodyClass'); ?>">
        <div id="wrapper">
            <?php print $this->partial('common/header.phtml'); ?>
            <div id="content">
                <div id="body">
                    <div class="innerwrap">
                    <?php print $this->layout()->content; ?>
                    </div>
                </div>
                <?php print $this->partial('common/navigation.phtml'); ?>
            </div>
        </div>
        <!-- /#wrapper -->
        <?php print $this->partial('common/footer.phtml'); ?>
    </body>
</html>