
<div id="colophon">
<!-- footer template -->
<?php
    $generalMenu = $this->navigation()->findOneByLabel('General Pages');
    $businessPagesMenu = $this->navigation()->findOneByLabel('Business Pages');
?>
<div>
    <?php $auth = Zend_Auth::getInstance(); ?>
    <?php if ($auth->hasIdentity()): ?>
        <?php
            print $this->navigation()
                       ->menu()
                       ->renderMenu($generalMenu);
        ?>
    <?php endif;?>
</div>
<div>
    <?php $auth = Zend_Auth::getInstance(); ?>
    <?php if ($auth->hasIdentity()): ?>
        <?php
            print $this->navigation()
                       ->menu()
                       ->renderMenu($businessPagesMenu);
        ?>
    <?php endif;?>
</div>
<div id="copyright">
    &copy; copyright <?php echo date('Y'); ?> <a href='http://www.matthewsetter.com'>Matthew Setter</a>. All rights reserved.
</div>
</div>